/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedClassificaRouteImport } from './routes/_authenticated/classifica'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedLeaderboardRouteImport } from './routes/_authenticated/leaderboard'
import { Route as AuthenticatedMarketplaceRouteImport } from './routes/_authenticated/marketplace'
import { Route as AuthenticatedResocontoRouteImport } from './routes/_authenticated/resoconto'
import { Route as AuthenticatedStoricoRouteImport } from './routes/_authenticated/storico'
import { Route as AuthenticatedTappeRouteImport } from './routes/_authenticated/tappe'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin/analytics'
import { Route as AuthenticatedAdminBoxeRouteImport } from './routes/_authenticated/admin/boxe'
import { Route as AuthenticatedAdminClassificaRouteImport } from './routes/_authenticated/admin/classifica'
import { Route as AuthenticatedAdminCornholeRouteImport } from './routes/_authenticated/admin/cornhole'
import { Route as AuthenticatedAdminEnigmiRouteImport } from './routes/_authenticated/admin/enigmi'
import { Route as AuthenticatedAdminJackpotRouteImport } from './routes/_authenticated/admin/jackpot'
import { Route as AuthenticatedAdminMarketplaceRouteImport } from './routes/_authenticated/admin/marketplace'
import { Route as AuthenticatedAdminOverviewRouteImport } from './routes/_authenticated/admin/overview'
import { Route as AuthenticatedAdminPartenzeRouteImport } from './routes/_authenticated/admin/partenze'
import { Route as AuthenticatedAdminPassaparolaRouteImport } from './routes/_authenticated/admin/passaparola'
import { Route as AuthenticatedAdminPenalitaRouteImport } from './routes/_authenticated/admin/penalita'
import { Route as AuthenticatedAdminPhotosRouteImport } from './routes/_authenticated/admin/photos'
import { Route as AuthenticatedAdminPostersRouteImport } from './routes/_authenticated/admin/posters'
import { Route as AuthenticatedAdminResocontoRouteImport } from './routes/_authenticated/admin/resoconto'
import { Route as AuthenticatedAdminSecretCodeRouteImport } from './routes/_authenticated/admin/secret-code'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminSocialRouteImport } from './routes/_authenticated/admin/social'
import { Route as AuthenticatedAdminTassaRouteImport } from './routes/_authenticated/admin/tassa'
import { Route as AuthenticatedAdminTeamsRouteImport } from './routes/_authenticated/admin/teams'
import { Route as AuthenticatedChallengeChallengeIdRouteImport } from './routes/_authenticated/challenge.$challengeId'
import { Route as AuthenticatedStageStageIdRouteImport } from './routes/_authenticated/stage.$stageId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClassificaRoute = AuthenticatedClassificaRouteImport.update({
  id: '/classifica',
  path: '/classifica',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeaderboardRoute =
  AuthenticatedLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMarketplaceRoute =
  AuthenticatedMarketplaceRouteImport.update({
    id: '/marketplace',
    path: '/marketplace',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedResocontoRoute = AuthenticatedResocontoRouteImport.update({
  id: '/resoconto',
  path: '/resoconto',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStoricoRoute = AuthenticatedStoricoRouteImport.update({
  id: '/storico',
  path: '/storico',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTappeRoute = AuthenticatedTappeRouteImport.update({
  id: '/tappe',
  path: '/tappe',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBoxeRoute = AuthenticatedAdminBoxeRouteImport.update({
  id: '/boxe',
  path: '/boxe',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminClassificaRoute =
  AuthenticatedAdminClassificaRouteImport.update({
    id: '/classifica',
    path: '/classifica',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCornholeRoute =
  AuthenticatedAdminCornholeRouteImport.update({
    id: '/cornhole',
    path: '/cornhole',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEnigmiRoute =
  AuthenticatedAdminEnigmiRouteImport.update({
    id: '/enigmi',
    path: '/enigmi',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminJackpotRoute =
  AuthenticatedAdminJackpotRouteImport.update({
    id: '/jackpot',
    path: '/jackpot',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMarketplaceRoute =
  AuthenticatedAdminMarketplaceRouteImport.update({
    id: '/marketplace',
    path: '/marketplace',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOverviewRoute =
  AuthenticatedAdminOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPartenzeRoute =
  AuthenticatedAdminPartenzeRouteImport.update({
    id: '/partenze',
    path: '/partenze',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPassaparolaRoute =
  AuthenticatedAdminPassaparolaRouteImport.update({
    id: '/passaparola',
    path: '/passaparola',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPenalitaRoute =
  AuthenticatedAdminPenalitaRouteImport.update({
    id: '/penalita',
    path: '/penalita',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPhotosRoute =
  AuthenticatedAdminPhotosRouteImport.update({
    id: '/photos',
    path: '/photos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPostersRoute =
  AuthenticatedAdminPostersRouteImport.update({
    id: '/posters',
    path: '/posters',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminResocontoRoute =
  AuthenticatedAdminResocontoRouteImport.update({
    id: '/resoconto',
    path: '/resoconto',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSecretCodeRoute =
  AuthenticatedAdminSecretCodeRouteImport.update({
    id: '/secret-code',
    path: '/secret-code',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSocialRoute =
  AuthenticatedAdminSocialRouteImport.update({
    id: '/social',
    path: '/social',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTassaRoute = AuthenticatedAdminTassaRouteImport.update({
  id: '/tassa',
  path: '/tassa',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminTeamsRoute = AuthenticatedAdminTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedChallengeChallengeIdRoute =
  AuthenticatedChallengeChallengeIdRouteImport.update({
    id: '/challenge/$challengeId',
    path: '/challenge/$challengeId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStageStageIdRoute =
  AuthenticatedStageStageIdRouteImport.update({
    id: '/stage/$stageId',
    path: '/stage/$stageId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/classifica': typeof AuthenticatedClassificaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/marketplace': typeof AuthenticatedMarketplaceRoute
  '/resoconto': typeof AuthenticatedResocontoRoute
  '/storico': typeof AuthenticatedStoricoRoute
  '/tappe': typeof AuthenticatedTappeRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/boxe': typeof AuthenticatedAdminBoxeRoute
  '/admin/classifica': typeof AuthenticatedAdminClassificaRoute
  '/admin/cornhole': typeof AuthenticatedAdminCornholeRoute
  '/admin/enigmi': typeof AuthenticatedAdminEnigmiRoute
  '/admin/jackpot': typeof AuthenticatedAdminJackpotRoute
  '/admin/marketplace': typeof AuthenticatedAdminMarketplaceRoute
  '/admin/overview': typeof AuthenticatedAdminOverviewRoute
  '/admin/partenze': typeof AuthenticatedAdminPartenzeRoute
  '/admin/passaparola': typeof AuthenticatedAdminPassaparolaRoute
  '/admin/penalita': typeof AuthenticatedAdminPenalitaRoute
  '/admin/photos': typeof AuthenticatedAdminPhotosRoute
  '/admin/posters': typeof AuthenticatedAdminPostersRoute
  '/admin/resoconto': typeof AuthenticatedAdminResocontoRoute
  '/admin/secret-code': typeof AuthenticatedAdminSecretCodeRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/social': typeof AuthenticatedAdminSocialRoute
  '/admin/tassa': typeof AuthenticatedAdminTassaRoute
  '/admin/teams': typeof AuthenticatedAdminTeamsRoute
  '/challenge/$challengeId': typeof AuthenticatedChallengeChallengeIdRoute
  '/stage/$stageId': typeof AuthenticatedStageStageIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/classifica': typeof AuthenticatedClassificaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/marketplace': typeof AuthenticatedMarketplaceRoute
  '/resoconto': typeof AuthenticatedResocontoRoute
  '/storico': typeof AuthenticatedStoricoRoute
  '/tappe': typeof AuthenticatedTappeRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/boxe': typeof AuthenticatedAdminBoxeRoute
  '/admin/classifica': typeof AuthenticatedAdminClassificaRoute
  '/admin/cornhole': typeof AuthenticatedAdminCornholeRoute
  '/admin/enigmi': typeof AuthenticatedAdminEnigmiRoute
  '/admin/jackpot': typeof AuthenticatedAdminJackpotRoute
  '/admin/marketplace': typeof AuthenticatedAdminMarketplaceRoute
  '/admin/overview': typeof AuthenticatedAdminOverviewRoute
  '/admin/partenze': typeof AuthenticatedAdminPartenzeRoute
  '/admin/passaparola': typeof AuthenticatedAdminPassaparolaRoute
  '/admin/penalita': typeof AuthenticatedAdminPenalitaRoute
  '/admin/photos': typeof AuthenticatedAdminPhotosRoute
  '/admin/posters': typeof AuthenticatedAdminPostersRoute
  '/admin/resoconto': typeof AuthenticatedAdminResocontoRoute
  '/admin/secret-code': typeof AuthenticatedAdminSecretCodeRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/social': typeof AuthenticatedAdminSocialRoute
  '/admin/tassa': typeof AuthenticatedAdminTassaRoute
  '/admin/teams': typeof AuthenticatedAdminTeamsRoute
  '/challenge/$challengeId': typeof AuthenticatedChallengeChallengeIdRoute
  '/stage/$stageId': typeof AuthenticatedStageStageIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/classifica': typeof AuthenticatedClassificaRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/_authenticated/marketplace': typeof AuthenticatedMarketplaceRoute
  '/_authenticated/resoconto': typeof AuthenticatedResocontoRoute
  '/_authenticated/storico': typeof AuthenticatedStoricoRoute
  '/_authenticated/tappe': typeof AuthenticatedTappeRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/boxe': typeof AuthenticatedAdminBoxeRoute
  '/_authenticated/admin/classifica': typeof AuthenticatedAdminClassificaRoute
  '/_authenticated/admin/cornhole': typeof AuthenticatedAdminCornholeRoute
  '/_authenticated/admin/enigmi': typeof AuthenticatedAdminEnigmiRoute
  '/_authenticated/admin/jackpot': typeof AuthenticatedAdminJackpotRoute
  '/_authenticated/admin/marketplace': typeof AuthenticatedAdminMarketplaceRoute
  '/_authenticated/admin/overview': typeof AuthenticatedAdminOverviewRoute
  '/_authenticated/admin/partenze': typeof AuthenticatedAdminPartenzeRoute
  '/_authenticated/admin/passaparola': typeof AuthenticatedAdminPassaparolaRoute
  '/_authenticated/admin/penalita': typeof AuthenticatedAdminPenalitaRoute
  '/_authenticated/admin/photos': typeof AuthenticatedAdminPhotosRoute
  '/_authenticated/admin/posters': typeof AuthenticatedAdminPostersRoute
  '/_authenticated/admin/resoconto': typeof AuthenticatedAdminResocontoRoute
  '/_authenticated/admin/secret-code': typeof AuthenticatedAdminSecretCodeRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/social': typeof AuthenticatedAdminSocialRoute
  '/_authenticated/admin/tassa': typeof AuthenticatedAdminTassaRoute
  '/_authenticated/admin/teams': typeof AuthenticatedAdminTeamsRoute
  '/_authenticated/challenge/$challengeId': typeof AuthenticatedChallengeChallengeIdRoute
  '/_authenticated/stage/$stageId': typeof AuthenticatedStageStageIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/classifica'
    | '/dashboard'
    | '/leaderboard'
    | '/marketplace'
    | '/resoconto'
    | '/storico'
    | '/tappe'
    | '/admin/analytics'
    | '/admin/boxe'
    | '/admin/classifica'
    | '/admin/cornhole'
    | '/admin/enigmi'
    | '/admin/jackpot'
    | '/admin/marketplace'
    | '/admin/overview'
    | '/admin/partenze'
    | '/admin/passaparola'
    | '/admin/penalita'
    | '/admin/photos'
    | '/admin/posters'
    | '/admin/resoconto'
    | '/admin/secret-code'
    | '/admin/settings'
    | '/admin/social'
    | '/admin/tassa'
    | '/admin/teams'
    | '/challenge/$challengeId'
    | '/stage/$stageId'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/classifica'
    | '/dashboard'
    | '/leaderboard'
    | '/marketplace'
    | '/resoconto'
    | '/storico'
    | '/tappe'
    | '/admin/analytics'
    | '/admin/boxe'
    | '/admin/classifica'
    | '/admin/cornhole'
    | '/admin/enigmi'
    | '/admin/jackpot'
    | '/admin/marketplace'
    | '/admin/overview'
    | '/admin/partenze'
    | '/admin/passaparola'
    | '/admin/penalita'
    | '/admin/photos'
    | '/admin/posters'
    | '/admin/resoconto'
    | '/admin/secret-code'
    | '/admin/settings'
    | '/admin/social'
    | '/admin/tassa'
    | '/admin/teams'
    | '/challenge/$challengeId'
    | '/stage/$stageId'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/classifica'
    | '/_authenticated/dashboard'
    | '/_authenticated/leaderboard'
    | '/_authenticated/marketplace'
    | '/_authenticated/resoconto'
    | '/_authenticated/storico'
    | '/_authenticated/tappe'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/boxe'
    | '/_authenticated/admin/classifica'
    | '/_authenticated/admin/cornhole'
    | '/_authenticated/admin/enigmi'
    | '/_authenticated/admin/jackpot'
    | '/_authenticated/admin/marketplace'
    | '/_authenticated/admin/overview'
    | '/_authenticated/admin/partenze'
    | '/_authenticated/admin/passaparola'
    | '/_authenticated/admin/penalita'
    | '/_authenticated/admin/photos'
    | '/_authenticated/admin/posters'
    | '/_authenticated/admin/resoconto'
    | '/_authenticated/admin/secret-code'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/social'
    | '/_authenticated/admin/tassa'
    | '/_authenticated/admin/teams'
    | '/_authenticated/challenge/$challengeId'
    | '/_authenticated/stage/$stageId'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/classifica': {
      id: '/_authenticated/classifica'
      path: '/classifica'
      fullPath: '/classifica'
      preLoaderRoute: typeof AuthenticatedClassificaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leaderboard': {
      id: '/_authenticated/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthenticatedLeaderboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketplace': {
      id: '/_authenticated/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof AuthenticatedMarketplaceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resoconto': {
      id: '/_authenticated/resoconto'
      path: '/resoconto'
      fullPath: '/resoconto'
      preLoaderRoute: typeof AuthenticatedResocontoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/storico': {
      id: '/_authenticated/storico'
      path: '/storico'
      fullPath: '/storico'
      preLoaderRoute: typeof AuthenticatedStoricoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tappe': {
      id: '/_authenticated/tappe'
      path: '/tappe'
      fullPath: '/tappe'
      preLoaderRoute: typeof AuthenticatedTappeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/boxe': {
      id: '/_authenticated/admin/boxe'
      path: '/boxe'
      fullPath: '/admin/boxe'
      preLoaderRoute: typeof AuthenticatedAdminBoxeRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/classifica': {
      id: '/_authenticated/admin/classifica'
      path: '/classifica'
      fullPath: '/admin/classifica'
      preLoaderRoute: typeof AuthenticatedAdminClassificaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/cornhole': {
      id: '/_authenticated/admin/cornhole'
      path: '/cornhole'
      fullPath: '/admin/cornhole'
      preLoaderRoute: typeof AuthenticatedAdminCornholeRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/enigmi': {
      id: '/_authenticated/admin/enigmi'
      path: '/enigmi'
      fullPath: '/admin/enigmi'
      preLoaderRoute: typeof AuthenticatedAdminEnigmiRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/jackpot': {
      id: '/_authenticated/admin/jackpot'
      path: '/jackpot'
      fullPath: '/admin/jackpot'
      preLoaderRoute: typeof AuthenticatedAdminJackpotRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/marketplace': {
      id: '/_authenticated/admin/marketplace'
      path: '/marketplace'
      fullPath: '/admin/marketplace'
      preLoaderRoute: typeof AuthenticatedAdminMarketplaceRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/overview': {
      id: '/_authenticated/admin/overview'
      path: '/overview'
      fullPath: '/admin/overview'
      preLoaderRoute: typeof AuthenticatedAdminOverviewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/partenze': {
      id: '/_authenticated/admin/partenze'
      path: '/partenze'
      fullPath: '/admin/partenze'
      preLoaderRoute: typeof AuthenticatedAdminPartenzeRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/passaparola': {
      id: '/_authenticated/admin/passaparola'
      path: '/passaparola'
      fullPath: '/admin/passaparola'
      preLoaderRoute: typeof AuthenticatedAdminPassaparolaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/penalita': {
      id: '/_authenticated/admin/penalita'
      path: '/penalita'
      fullPath: '/admin/penalita'
      preLoaderRoute: typeof AuthenticatedAdminPenalitaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/photos': {
      id: '/_authenticated/admin/photos'
      path: '/photos'
      fullPath: '/admin/photos'
      preLoaderRoute: typeof AuthenticatedAdminPhotosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/posters': {
      id: '/_authenticated/admin/posters'
      path: '/posters'
      fullPath: '/admin/posters'
      preLoaderRoute: typeof AuthenticatedAdminPostersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/resoconto': {
      id: '/_authenticated/admin/resoconto'
      path: '/resoconto'
      fullPath: '/admin/resoconto'
      preLoaderRoute: typeof AuthenticatedAdminResocontoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/secret-code': {
      id: '/_authenticated/admin/secret-code'
      path: '/secret-code'
      fullPath: '/admin/secret-code'
      preLoaderRoute: typeof AuthenticatedAdminSecretCodeRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/social': {
      id: '/_authenticated/admin/social'
      path: '/social'
      fullPath: '/admin/social'
      preLoaderRoute: typeof AuthenticatedAdminSocialRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/tassa': {
      id: '/_authenticated/admin/tassa'
      path: '/tassa'
      fullPath: '/admin/tassa'
      preLoaderRoute: typeof AuthenticatedAdminTassaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/teams': {
      id: '/_authenticated/admin/teams'
      path: '/teams'
      fullPath: '/admin/teams'
      preLoaderRoute: typeof AuthenticatedAdminTeamsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/challenge/$challengeId': {
      id: '/_authenticated/challenge/$challengeId'
      path: '/challenge/$challengeId'
      fullPath: '/challenge/$challengeId'
      preLoaderRoute: typeof AuthenticatedChallengeChallengeIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stage/$stageId': {
      id: '/_authenticated/stage/$stageId'
      path: '/stage/$stageId'
      fullPath: '/stage/$stageId'
      preLoaderRoute: typeof AuthenticatedStageStageIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminBoxeRoute: typeof AuthenticatedAdminBoxeRoute
  AuthenticatedAdminClassificaRoute: typeof AuthenticatedAdminClassificaRoute
  AuthenticatedAdminCornholeRoute: typeof AuthenticatedAdminCornholeRoute
  AuthenticatedAdminEnigmiRoute: typeof AuthenticatedAdminEnigmiRoute
  AuthenticatedAdminJackpotRoute: typeof AuthenticatedAdminJackpotRoute
  AuthenticatedAdminMarketplaceRoute: typeof AuthenticatedAdminMarketplaceRoute
  AuthenticatedAdminOverviewRoute: typeof AuthenticatedAdminOverviewRoute
  AuthenticatedAdminPartenzeRoute: typeof AuthenticatedAdminPartenzeRoute
  AuthenticatedAdminPassaparolaRoute: typeof AuthenticatedAdminPassaparolaRoute
  AuthenticatedAdminPenalitaRoute: typeof AuthenticatedAdminPenalitaRoute
  AuthenticatedAdminPhotosRoute: typeof AuthenticatedAdminPhotosRoute
  AuthenticatedAdminPostersRoute: typeof AuthenticatedAdminPostersRoute
  AuthenticatedAdminResocontoRoute: typeof AuthenticatedAdminResocontoRoute
  AuthenticatedAdminSecretCodeRoute: typeof AuthenticatedAdminSecretCodeRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminSocialRoute: typeof AuthenticatedAdminSocialRoute
  AuthenticatedAdminTassaRoute: typeof AuthenticatedAdminTassaRoute
  AuthenticatedAdminTeamsRoute: typeof AuthenticatedAdminTeamsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminBoxeRoute: AuthenticatedAdminBoxeRoute,
  AuthenticatedAdminClassificaRoute: AuthenticatedAdminClassificaRoute,
  AuthenticatedAdminCornholeRoute: AuthenticatedAdminCornholeRoute,
  AuthenticatedAdminEnigmiRoute: AuthenticatedAdminEnigmiRoute,
  AuthenticatedAdminJackpotRoute: AuthenticatedAdminJackpotRoute,
  AuthenticatedAdminMarketplaceRoute: AuthenticatedAdminMarketplaceRoute,
  AuthenticatedAdminOverviewRoute: AuthenticatedAdminOverviewRoute,
  AuthenticatedAdminPartenzeRoute: AuthenticatedAdminPartenzeRoute,
  AuthenticatedAdminPassaparolaRoute: AuthenticatedAdminPassaparolaRoute,
  AuthenticatedAdminPenalitaRoute: AuthenticatedAdminPenalitaRoute,
  AuthenticatedAdminPhotosRoute: AuthenticatedAdminPhotosRoute,
  AuthenticatedAdminPostersRoute: AuthenticatedAdminPostersRoute,
  AuthenticatedAdminResocontoRoute: AuthenticatedAdminResocontoRoute,
  AuthenticatedAdminSecretCodeRoute: AuthenticatedAdminSecretCodeRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminSocialRoute: AuthenticatedAdminSocialRoute,
  AuthenticatedAdminTassaRoute: AuthenticatedAdminTassaRoute,
  AuthenticatedAdminTeamsRoute: AuthenticatedAdminTeamsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedClassificaRoute: typeof AuthenticatedClassificaRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLeaderboardRoute: typeof AuthenticatedLeaderboardRoute
  AuthenticatedMarketplaceRoute: typeof AuthenticatedMarketplaceRoute
  AuthenticatedResocontoRoute: typeof AuthenticatedResocontoRoute
  AuthenticatedStoricoRoute: typeof AuthenticatedStoricoRoute
  AuthenticatedTappeRoute: typeof AuthenticatedTappeRoute
  AuthenticatedChallengeChallengeIdRoute: typeof AuthenticatedChallengeChallengeIdRoute
  AuthenticatedStageStageIdRoute: typeof AuthenticatedStageStageIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedClassificaRoute: AuthenticatedClassificaRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLeaderboardRoute: AuthenticatedLeaderboardRoute,
  AuthenticatedMarketplaceRoute: AuthenticatedMarketplaceRoute,
  AuthenticatedResocontoRoute: AuthenticatedResocontoRoute,
  AuthenticatedStoricoRoute: AuthenticatedStoricoRoute,
  AuthenticatedTappeRoute: AuthenticatedTappeRoute,
  AuthenticatedChallengeChallengeIdRoute:
    AuthenticatedChallengeChallengeIdRoute,
  AuthenticatedStageStageIdRoute: AuthenticatedStageStageIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
